version: '3.7'

services:
  codeBusters_habr_db:
    image: postgres:14.5
    container_name: codeBusters_habr_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - codeBusters_habr_db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  codeBusters_habr_db-data: null
